/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ClaimAdminRouteImport } from './routes/claim-admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AdminVerificationsRouteImport } from './routes/admin/verifications'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPetsRouteImport } from './routes/admin/pets'
import { Route as AdminLostRouteImport } from './routes/admin/lost'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AuthenticatedVaccinesRouteImport } from './routes/_authenticated/vaccines'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQrRouteImport } from './routes/_authenticated/qr'
import { Route as AuthenticatedPetsRouteImport } from './routes/_authenticated/pets'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedPetsNewRouteImport } from './routes/_authenticated/pets.new'
import { Route as AuthenticatedPetsIdRouteImport } from './routes/_authenticated/pets.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimAdminRoute = ClaimAdminRouteImport.update({
  id: '/claim-admin',
  path: '/claim-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPetsRoute = AdminPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLostRoute = AdminLostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedVaccinesRoute = AuthenticatedVaccinesRouteImport.update({
  id: '/vaccines',
  path: '/vaccines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrRoute = AuthenticatedQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetsRoute = AuthenticatedPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPetsNewRoute = AuthenticatedPetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedPetsRoute,
} as any)
const AuthenticatedPetsIdRoute = AuthenticatedPetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/claim-admin': typeof ClaimAdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/pets': typeof AuthenticatedPetsRouteWithChildren
  '/qr': typeof AuthenticatedQrRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vaccines': typeof AuthenticatedVaccinesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/lost': typeof AdminLostRoute
  '/admin/pets': typeof AdminPetsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/pets/$id': typeof AuthenticatedPetsIdRoute
  '/pets/new': typeof AuthenticatedPetsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/claim-admin': typeof ClaimAdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/pets': typeof AuthenticatedPetsRouteWithChildren
  '/qr': typeof AuthenticatedQrRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vaccines': typeof AuthenticatedVaccinesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/lost': typeof AdminLostRoute
  '/admin/pets': typeof AdminPetsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/p/$slug': typeof PSlugRoute
  '/admin': typeof AdminIndexRoute
  '/pets/$id': typeof AuthenticatedPetsIdRoute
  '/pets/new': typeof AuthenticatedPetsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/claim-admin': typeof ClaimAdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/pets': typeof AuthenticatedPetsRouteWithChildren
  '/_authenticated/qr': typeof AuthenticatedQrRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/vaccines': typeof AuthenticatedVaccinesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/lost': typeof AdminLostRoute
  '/admin/pets': typeof AdminPetsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/pets/$id': typeof AuthenticatedPetsIdRoute
  '/_authenticated/pets/new': typeof AuthenticatedPetsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/claim-admin'
    | '/reset-password'
    | '/appointments'
    | '/dashboard'
    | '/documents'
    | '/pets'
    | '/qr'
    | '/settings'
    | '/vaccines'
    | '/admin/audit'
    | '/admin/lost'
    | '/admin/pets'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/admin/verifications'
    | '/p/$slug'
    | '/admin/'
    | '/pets/$id'
    | '/pets/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/claim-admin'
    | '/reset-password'
    | '/appointments'
    | '/dashboard'
    | '/documents'
    | '/pets'
    | '/qr'
    | '/settings'
    | '/vaccines'
    | '/admin/audit'
    | '/admin/lost'
    | '/admin/pets'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/admin/verifications'
    | '/p/$slug'
    | '/admin'
    | '/pets/$id'
    | '/pets/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/claim-admin'
    | '/reset-password'
    | '/_authenticated/appointments'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/pets'
    | '/_authenticated/qr'
    | '/_authenticated/settings'
    | '/_authenticated/vaccines'
    | '/admin/audit'
    | '/admin/lost'
    | '/admin/pets'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/admin/verifications'
    | '/p/$slug'
    | '/admin/'
    | '/_authenticated/pets/$id'
    | '/_authenticated/pets/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClaimAdminRoute: typeof ClaimAdminRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-admin': {
      id: '/claim-admin'
      path: '/claim-admin'
      fullPath: '/claim-admin'
      preLoaderRoute: typeof ClaimAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pets': {
      id: '/admin/pets'
      path: '/pets'
      fullPath: '/admin/pets'
      preLoaderRoute: typeof AdminPetsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lost': {
      id: '/admin/lost'
      path: '/lost'
      fullPath: '/admin/lost'
      preLoaderRoute: typeof AdminLostRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/vaccines': {
      id: '/_authenticated/vaccines'
      path: '/vaccines'
      fullPath: '/vaccines'
      preLoaderRoute: typeof AuthenticatedVaccinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr': {
      id: '/_authenticated/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof AuthenticatedQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets': {
      id: '/_authenticated/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof AuthenticatedPetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets/new': {
      id: '/_authenticated/pets/new'
      path: '/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof AuthenticatedPetsNewRouteImport
      parentRoute: typeof AuthenticatedPetsRoute
    }
    '/_authenticated/pets/$id': {
      id: '/_authenticated/pets/$id'
      path: '/$id'
      fullPath: '/pets/$id'
      preLoaderRoute: typeof AuthenticatedPetsIdRouteImport
      parentRoute: typeof AuthenticatedPetsRoute
    }
  }
}

interface AuthenticatedPetsRouteChildren {
  AuthenticatedPetsIdRoute: typeof AuthenticatedPetsIdRoute
  AuthenticatedPetsNewRoute: typeof AuthenticatedPetsNewRoute
}

const AuthenticatedPetsRouteChildren: AuthenticatedPetsRouteChildren = {
  AuthenticatedPetsIdRoute: AuthenticatedPetsIdRoute,
  AuthenticatedPetsNewRoute: AuthenticatedPetsNewRoute,
}

const AuthenticatedPetsRouteWithChildren =
  AuthenticatedPetsRoute._addFileChildren(AuthenticatedPetsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedPetsRoute: typeof AuthenticatedPetsRouteWithChildren
  AuthenticatedQrRoute: typeof AuthenticatedQrRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVaccinesRoute: typeof AuthenticatedVaccinesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedPetsRoute: AuthenticatedPetsRouteWithChildren,
  AuthenticatedQrRoute: AuthenticatedQrRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVaccinesRoute: AuthenticatedVaccinesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminLostRoute: typeof AdminLostRoute
  AdminPetsRoute: typeof AdminPetsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminLostRoute: AdminLostRoute,
  AdminPetsRoute: AdminPetsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClaimAdminRoute: ClaimAdminRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
